### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by E4zily** [wally-rblx/funky-friday-autoplay#10]
simply not working at all, changing chances does nothing

**Comment by E4zily** [comment]
took information from #9:

Can you provide the following information:
What song are you playing? kapi - nyaw (or any other)
What executor are you using? krnl
What side are you playing on (right, left)? left
no errors

**Comment by wally-rblx** [comment]
Seems to be an issue with Krnl.

**Comment by E4zily** [comment]
what executor should i use
