### ISSUE TITLE
suggestion revolving the bot itself

### ISSUE THREAD

**Issue by DeceptedParasite** [wally-rblx/funky-friday-autoplay#19]
if a hold note goes through an arrow it lets go and hits the note and does not keep holding
I'm sorry if this doesn't make sense

**Comment by DeceptedParasite** [comment]
basically why I want this to be added in is because of foolhardy's chart, there's a force miss due to the hold note going through a normal note

**Comment by greasemonkey123** [comment]
I have already suggested a fix @ Pull Request #17.
This has been fixed in [my fork](https://github.com/greasemonkey123/ff-mod-menu/blob/main/main.lua) which has a slider to control the outcome of Hold Notes. Setting it to anything between -40 to -20 would do the trick.
