### ISSUE TITLE
Autoplayer hitting notes too early

### ISSUE THREAD

**Issue by AlyssaTheCoder** [wally-rblx/funky-friday-autoplay#26]
https://user-images.githubusercontent.com/89949310/134789460-5bd77a34-f7f1-4e5d-8bc8-e4f9fa932869.mp4

I recorded this with ShareX instead of OBS because its less absolutely huge

**Comment by wally-rblx** [comment]
seems like you are using the forked version, i'll still take a look as it might be my issue.
please follow the bug report guide on the main page of this repository or join the discord server to discuss more about this bug. 
thanks.

**Comment by greasemonkey123** [comment]
Hey, I don't see the issue shown in the video. The accuracy is staying at 100% and you are still getting all sicks. Do you mean the issue is the timing one? (~ -10ms)
