### ISSUE TITLE
Nk when

### ISSUE THREAD

**Issue by imdoingthisfortheprofile** [wally-rblx/funky-friday-autoplay#30]
since they added 6, 7, and 9k, i just wanted to know when its gonna be added to the bot?

**Comment by kyqoz** [comment]
yes please do this i need to troll osu players

**Comment by imdoingthisfortheprofile** [comment]
...

**Comment by imdoingthisfortheprofile** [comment]
im asking for an answer not just closing it

**Comment by kyqoz** [comment]
it was released already before this thread was even made smart ass

**Comment by imdoingthisfortheprofile** [comment]
what was released? 9k hasnt been added to the script yet
