### ISSUE TITLE
Autoplayer hits death notes causing you to lose on expurgation.

### ISSUE THREAD

**Issue by stupidmobilerooter** [wally-rblx/funky-friday-autoplay#33]
Funky friday recently updated and added an experimental feature only on expurgation. This causes the autoplayer to hit the death notes causing the player using the script to die. Here is how the notes look like. 
![image](https://user-images.githubusercontent.com/96339196/146641525-407e0264-0943-4224-a7e8-01696d9c9977.png)

**Comment by HapJim** [comment]
theres probably some variable in the game that tells if its a death note. if you add in something to just ignore any note with "deathnote = true" or whatever itll probably work

**Comment by wally-rblx** [comment]
fixed
