### ISSUE TITLE
Bot hits new "pea notes"

### ISSUE THREAD

**Issue by HapJim** [wally-rblx/funky-friday-autoplay#40]
the bot hits a new notetype called "pea notes" which you're not supposed to hit
i found a fix for this though
instead of this:
if type(arrow.NoteDataConfigs) == 'table' and arrow.NoteDataConfigs.Type == 'Death' then
            continue
end
you can use this:
if type(arrow.NoteDataConfigs) == 'table' then
            if arrow.NoteDataConfigs.Type == 'Death' or arrow.NoteDataConfigs.Type == 'Pea Note' then 
                continue
            end
end

**Comment by wally-rblx** [comment]
fixed
