### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by Jes-debug** [wally-rblx/funky-friday-autoplay#41]
THE NEW UPDATE TO THE SCRIPT IS CONFUSING BC IT KEEPS HITTING THE UP BUTTON WHEN THEE ISNT EVEN ANY NOTES THERE AND I HAVE 100% SICK PLS FIX

**Comment by Jes-debug** [comment]
script ware m executor

**Comment by persekarva** [comment]
for me it gets 100 misses when there is no notes to hit...

**Comment by Jes-debug** [comment]
WHY U CLOSE

**Comment by Jes-debug** [comment]
HELP ME @wally-rblx
