### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Zhafranilhamj** [wally-rblx/funky-friday-autoplay#43]
when i actived the autoplayer it crashes my executor can execute but crash

**Comment by sabaasa** [comment]
ur executor sucks lol

**Comment by sabaasa** [comment]
what executor are you using?

**Comment by Zhafranilhamj** [comment]
I'm using fluxus

**Comment by Zhafranilhamj** [comment]
> ur executor sucks lol

Dude I'm using fluxus it supports fluxus
