### ISSUE TITLE
it no longer works

### ISSUE THREAD

**Issue by minecraftbotapk** [wally-rblx/funky-friday-autoplay#46]
when i execute there are errors in the f9 console and i dont see any auto player 
my executer is novaline it worked in the past but now its not working

**Comment by Mati278** [comment]
try using krnl

**Comment by Jes-debug** [comment]
im using a PAID executor, it must be the script

**Comment by Jes-debug** [comment]
found a fix, get the script from [here](https://github.com/wally-rblx/funky-friday-autoplay/blob/459fd1b6ef9aaa2bc23c4237d2091232016cc92c/main.lua)
