### ISSUE TITLE
BUG! Ink Notes can still be HIT and also Death Notes?

### ISSUE THREAD

**Issue by Reeeeeeeeeeeeeeeee231** [wally-rblx/funky-friday-autoplay#49]
Hiya! I found a bug. At the 1 Minute and 43 seconds mark there is a part where it hits the ink notes and misses and later on in the song you actually die of a death note. Please fix! 

Here a link to a video that might help:  https://www.youtube.com/watch?v=3kftshjBbI8&ab_channel=HeckerII

I'm using Synapse X and I was on the right side!

**Comment by Reeeeeeeeeeeeeeeee231** [comment]
> At the 1 Minute and 37 seconds mark there is a part where it hits the ink notes and misses and later on in the song you actually die of a death note. Please fix!
> 
> Here a link to a video that might help: https://www.youtube.com/watch?v=3kftshjBbI8&ab_channel=HeckerII

I'm using Synapse X and I was on the right side!

**Comment by B01Coding** [comment]
is outdated dumb
