### ISSUE TITLE
it didn't work

### ISSUE THREAD

**Issue by rgradithya01** [wally-rblx/funky-friday-autoplay#50]
I'm using jjsploit v6.4.9 in Windows 11, I used your script but it didn't work instead i got a "fatal error".

**Comment by zachybee123** [comment]
jjsploit is a bitcoin miner DONT USE IT BECAUSE ITS TRASH AND THE OWNER MADE IT FOR MONEY PLEASE SWITCH TO KRNL OR ATLEAST USE SYNAPSE

**Comment by bloodyrose0** [comment]
> jjsploit is a bitcoin miner DONT USE IT BECAUSE ITS TRASH AND THE OWNER MADE IT FOR MONEY PLEASE SWITCH TO KRNL OR ATLEAST USE SYNAPSE

sorry im late but thanks man, i've been using krnl for 4 months now.
