### ISSUE TITLE
Script doesn't work after roblox update

### ISSUE THREAD

**Issue by BlackxNerm** [wally-rblx/funky-friday-autoplay#9]
Can you update it? i wanna troll someone

**Comment by wally-rblx** [comment]
Hello! Thank you for reporting this issue to me.
It seems to work fine for me in a VIP server, although maybe there's some specific case I'm not triggering.

Can you provide the following information:
What song are you playing?
What executor are you using?
What side are you playing on (right, left)?
(optional) A video showcase of you using it and it not working (upload to streamable or youtube)
(optional) A screenshot of any errors in F9 console or Synapse X internal console.

Video of me using it this morning: https://streamable.com/ah5d1s

**Comment by wally-rblx** [comment]
Seems to be an issue with Krnl.
